package com.redhat.batigerteam.examples;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-10-29T16:47:55.587-04:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://examples.batigerteam.redhat.com/", name = "SampleWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface SampleWebService {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://examples.batigerteam.redhat.com/", className = "com.redhat.batigerteam.examples.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://examples.batigerteam.redhat.com/", className = "com.redhat.batigerteam.examples.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
