package com.redhat.batigerteam.examples;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-10-29T16:47:55.592-04:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "SampleWebServiceService",
                  wsdlLocation = "file:src/main/resources/SampleWebService.wsdl",
                  targetNamespace = "http://examples.batigerteam.redhat.com/")
public class SampleWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://examples.batigerteam.redhat.com/", "SampleWebServiceService");
    public final static QName SampleWebServicePort = new QName("http://examples.batigerteam.redhat.com/", "SampleWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/SampleWebService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SampleWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:src/main/resources/SampleWebService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SampleWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SampleWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SampleWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SampleWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SampleWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SampleWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SampleWebService
     */
    @WebEndpoint(name = "SampleWebServicePort")
    public SampleWebService getSampleWebServicePort() {
        return super.getPort(SampleWebServicePort, SampleWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SampleWebService
     */
    @WebEndpoint(name = "SampleWebServicePort")
    public SampleWebService getSampleWebServicePort(WebServiceFeature... features) {
        return super.getPort(SampleWebServicePort, SampleWebService.class, features);
    }

}
